### ISSUE TITLE
invalid value (table) at index 1 in table for 'concat'

### ISSUE THREAD

**Issue by mdebski** [KSDaemon/Loowy#2]
Hi,

I get an error as follows in a basic client with lua-websockets v2.1-1, lua 5.1. It seems that you pass a table of protocols, while ws:connect expects just one. It worked for me when I changed this [0] line to read:
ws:connect(cache.url, cache.protocols[1])
so I just selected first element.

Do you think it is a bug and the solution is fine? Or is this some how intended?

Thanks!

[0] https://github.com/KSDaemon/Loowy/blob/master/src/loowy/client.lua#L875

CALLBACK FAILED: /usr/local/share/lua/5.1/websocket/handshake.lua:53: invalid value (table) at index 1 in table for 'concat'
stack traceback:
    [C]: in function 'concat'
    /usr/local/share/lua/5.1/websocket/handshake.lua:53: in function 'upgrade_request'
    /usr/local/share/lua/5.1/websocket/client_ev.lua:133: in function </usr/local/share/lua/5.1/websocket/client_ev.lua:129>
    [C]: in function 'loop'
    client.lua:29: in main chunk
    [C]: ?

**Comment by KSDaemon** [comment]
Hi, @mdebski!
Hmmm... Well, first of all: you solution is bad. WS RFC says, that a client can specify an array of supported subprotocols, so server can choose an appropriate variant. And i've added a such feature to lua-websockets here: https://github.com/lipp/lua-websockets/commit/59474ece0319b4b190469cb1afe838aca5f987b6

I'll try to check issue ASAP.

**Comment by mdebski** [comment]
Ok, that's fine then, your patch to lua-websockets seems to fix the issue.
It is not included in last release, I'll need to use git master.

On the other hand though... With lua-websockets@master and loowy@0.1.1-1 I get another error which seems to be closely related:

CALLBACK FAILED: /usr/local/share/lua/5.1/loowy/client.lua:388: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
    [C]: in function 'match'
    /usr/local/share/lua/5.1/loowy/client.lua:388: in function '_wsOnOpen'
    /usr/local/share/lua/5.1/loowy/client.lua:776: in function 'user_on_open'
    /usr/local/share/lua/5.1/websocket/client_ev.lua:73: in function 'on_open'
    /usr/local/share/lua/5.1/websocket/client_ev.lua:186: in function </usr/local/share/lua/5.1/websocket/client_ev.lua:152>
    [C]: in function 'loop'
    client.lua:29: in main chunk

on_open calls user_on_open with just one arguments, while it expects 3, second being wsProtocol, which is later string.match'ed.

Many thanks for your help!

**Comment by KSDaemon** [comment]
Ough! I see, it's been merged, but not published through luarocks.
About next problem — there is https://github.com/lipp/lua-websockets/pull/73 — which is not merged for a long time. The problem is — that client also expect to receive a selected subprotocol.

**Comment by KSDaemon** [comment]
@mdebski can you take code form my fork https://github.com/KSDaemon/lua-websockets and check is it working as expected?

**Comment by mdebski** [comment]
It works a bit better, at least it does not throw any lua errors. However, I get protocol errors from router instead:

> invalid role 'dealer' in 'roles' in 'details' in HELLO

I'm using crossbar.io as router. It seems that really loowy sends "dealer" and "broker" as roles in HELLO:

> localhost:34516 -> localhost:8080
> [1,"realm1",{"roles":{"dealer":{"features":{"callee_blackwhite_listing":true,"caller_exclusion":true,"caller_identification":true}},"broker":{"features":{"publisher_exclusion":true,"subscriber_blackwhite_listing":true,"publisher_identification":true}}},"agent":"Loowy\/Lua v0.1.1"}]

And crossbar complains, and seems to be right taking into account the [WAMP draft](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#page-28) (7.1.1.1), or I misunderstand something.

**Comment by KSDaemon** [comment]
Ou... I've just checked that out. Yes, Loowy seems to be a little bit outdated. I'll fix that.

**Comment by mdebski** [comment]
Thanks!

**Comment by KSDaemon** [comment]
@mdebski Also published new version to luarocks. https://luarocks.org/modules/ksdaemon/loowy
But remeber, that you need to patch original lipps lua-websockets for now...
